### ISSUE TITLE
Validity of `zimit` flags are not checked at recipe creation

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit-frontend#40] opened 2023-11-04 16:55 UTC
I can put a `Description` which is (for example) longer than 80 characters. This makes the scrape process to die.

UI inputs setting up ZIM metadata should be checked, ideally at user input time, to secure they match [our requirements](https://wiki.openzim.org/wiki/Metadata).

**Comment by benoit74** [comment] 2023-11-06 07:12
This is most probably a regression on Zimfarm, the farm should not accept a task with such a description. I'm checking this.
Checking field length at user input time has not been implemented so far, the UI has no information about expected maximum length, API is not providing this information.
I would suggest to split this second part of the issue, since this would probably be implemented in a second effort (while first part is very important AFAIK)

**Comment by benoit74** [comment] 2023-11-06 08:15
Second part is already tracked here indeed: https://github.com/openzim/zimfarm/issues/835

**Comment by benoit74** [comment] 2023-11-06 08:18
Second part tracked here now: https://github.com/openzim/zimit-frontend/issues/41

**Comment by benoit74** [comment] 2023-11-06 11:49
First part of this issue has been fixed and deployed [upstream](https://github.com/openzim/zimfarm/issues/864) 

But it looks like it is not really nicely handled in zimit UI, I'm looking into it:
![image](https://github.com/openzim/zimit-frontend/assets/7102089/e0f9495e-0562-4085-94ed-ce02125872c1)

**Comment by benoit74** [comment] 2023-11-06 11:53
This is indeed intentional in zimit-frontend code ; I will close this issue (we cannot set description too long anymore) and open another one to discuss 500 error specifically.

**Comment by benoit74** [comment] 2023-11-17 09:26
Fixed again by deployment of https://github.com/openzim/zimfarm/pull/868

**Closed by benoit74** 2023-11-17 09:26 UTC
Labels: enhancement, prio1
