### ISSUE TITLE
I can't create nice zim like before on zimit.kiwix

### ISSUE THREAD

**Issue by hamoudak** [openzim/zimit-frontend#59] opened 2024-06-26 17:44 UTC
in the last three or four days something strange happend when creating or browsing custom zim files.
first there was in the scraper info field just :  warc2zim and now I see zimit 2.0.3 + browsertrix  crawler 1.2.0 . I think this is an update or something related.  the main problem now is that (include field) not working as it was. not excluding any urls . sometimes it bypasses the given urls to include others, and with another website it takes a while to open pages in the created zim file. the web page interface styles and fonts changed completely by itself and not working well . could you please fix this; I 'll give you screenshots to confirm the issue.

this is the old one, working as expected, everything as on the web and it plays from the defined url .
(from page 84 to 70)

<img width="956" alt="the-old-one" src="https://github.com/openzim/zimit-frontend/assets/155604457/b3ca21a3-3047-4a54-99ed-9699848fd55e">

this is when everything has changed . when I play it, it won't start from the defined url (page 69)  I can't see it.
besides the other problems I have mentioned and more  .

<img width="954" alt="interface-fonts-styles-changed" src="https://github.com/openzim/zimit-frontend/assets/155604457/27ecb192-d085-43d0-995a-b09ebc33a274">

**Comment by benoit74** [comment] 2024-06-26 18:02
> in the last three or four days something strange happend when creating or browsing custom zim files.

We have rolled out progressively zimit2 and warc2zim2 over the last days / weeks indeed

> first there was in the scraper info field just : warc2zim and now I see zimit 2.0.3 + browsertrix crawler 1.2.0 

The old info was limited, you now have full details of the three tools used: zimit, crawler and warc2zim. Details of the discussion are in https://github.com/openzim/warc2zim/issues/156 and linked issues / PRs

> the main problem now is that (include field) not working as it was. not excluding any urls . sometimes it bypasses the given urls to include others, and with another website it takes a while to open pages in the created zim file. the web page interface styles and fonts changed completely by itself and not working well . could you please fix this; I 'll give you screenshots to confirm the issue.

We will need more info. Just sharing screenshots is not sufficient. Would you mind to share which parameters you are passing to zimit so that we can debug your issue? We already have ~40 ZIMs in production using the new version and they work like a charm, so it is not like we broke everything, but as with any big update I wouldn't be surprised there are few rough edges left.

**Comment by hamoudak** [comment] 2024-06-26 18:22
thank you for the info. this is the forum display link - https://majles.alukah.net/forumdisplay.php?f=20&page=69

I used to make these settings:

depth : 23
extra hops : 2
scope type : custom
include ( for instance) : 

^(https:\/\/)majles\.alukah\.net\/(forumdisplay\.php\?f=20&page=69|showthread\.php\?t=116871|showthread\.php\?t=116583|showthread\.php\?t=116535|showthread\.php\?t=5993|showthread\.php\?t=38855|showthread\.php\?t=61350|showthread\.php\?t=115601|showthread\.php\?t=114287|showthread\.php\?t=87903|showthread\.php\?t=65474|showthread\.php\?t=65474&page=2|showthread\.php\?t=114236|showthread\.php\?t=24131|showthread\.php\?t=24131&page=2|showthread\.php\?t=98807|showthread\.php\?t=113943|showthread\.php\?t=113941|showthread\.php\?t=113632|showthread\.php\?t=111602|showthread\.php\?t=71810|showthread\.php\?t=112191|showthread\.php\?t=112460|showthread\.php\?t=110898|showthread\.php\?t=77439|showthread\.php\?t=112926|showthread\.php\?t=112841|showthread\.php\?t=89471|showthread\.php\?t=112668|showthread\.php\?t=112676|showthread\.php\?t=111807|showthread\.php\?t=112546|showthread\.php\?t=98959|showthread\.php\?t=66322|showthread\.php\?t=66322&page=2|showthread\.php\?t=111913|showthread\.php\?t=111913&page=2|forumdisplay\.php\?f=20&page=68|showthread\.php\?t=119969|showthread\.php\?t=119888|showthread\.php\?t=118037|forumdisplay\.php\?f=20|forumdisplay\.php\?f=1|index\.php).*

**Comment by hamoudak** [comment] 2024-06-28 18:36
ok, I hope so.

**Comment by benoit74** [comment] 2024-07-01 08:29
OK so the change occurred because since Zimit 2 we use by default a technical setting to indicate the website we want the mobile version of the website, since most of our users are browsing ZIMs from mobile devices.

The website you are ZIMing is not dynamically adjusting its layout based on screen size, so the layout which is stored inside the ZIM is the mobile layout, and it does not adapt dynamically when the reader is finally browsing the ZIM from a big screen.

Should you want to return to previous "big screen" layout (which is probably ugly on mobile devices), you have to either set the `As Device` setting to a big screen device (probably in landscape)

![image](https://github.com/openzim/zimit-frontend/assets/7102089/81bb8ab0-89fa-4f95-9326-1feb06ab27c0)

Or you can restore Zimit1 behavior with the new setting "No Device" (I just added it few minutes ago to the UI, it was available in the scraper but not available from UI, it got forgotten). This setting is a bit dangerous since it means it will crawl at a default resolution (which currently is desktop, so it is fine, but it might change in the future), but this is probably OK for your usecase. Just tick the toggle to restore Zimit1 behavior.

![image](https://github.com/openzim/zimit-frontend/assets/7102089/06b236bc-3870-48b4-af54-9a52b6488649)

**Comment by hamoudak** [comment] 2024-07-01 16:29
thank you for clearing up this to me , I didn't know most of it, and for adding the "No device" setting .
 am using a laptop and browse zims on it all the time, so now am gonna try to use first "No device" then I'll check later "big screen" which is landscape. I hope it work as I did it before. I'll tell you the results after downloading one.

**Comment by hamoudak** [comment] 2024-07-01 20:16
It did work but I have noticed something; it takes sometime (ten seconds or thirteen) to open pages, what do about that?
when I leave the app sometime in the background then i go to open pages, it open fast for just one page.

<img width="956" alt="-test" src="https://github.com/openzim/zimit-frontend/assets/155604457/e8500a3e-ab0f-4d65-88a5-40406d5f2db6">

<img width="960" alt="new" src="https://github.com/openzim/zimit-frontend/assets/155604457/fd1c4a33-af7e-495b-a6fa-6d313d905f3a">

<img width="956" alt="new" src="https://github.com/openzim/zimit-frontend/assets/155604457/f0ff4b30-b9b9-460a-812f-ff59eb87d8b6">

**Comment by benoit74** [comment] 2024-07-01 20:27
Can you share a ZIM with us (preferably a - very - small one) so that we can confirm if the issue is linked to the Kiwix JS reader or to the Zimit scraper? (if it's ok for you, you can upload it to whatever upload service you would like, e.g. https://www.swisstransfer.com if you are looking for a safe one)

**Comment by benoit74** [comment] 2024-07-02 05:56
Thank you!

Unfortunately I'm not experiencing at all the slowness you're speaking about, not in Kiwix JS and not in Kiwix Apple (MacOS). This is going to be hard to diagnose.

Can you confirm you are using Kiwix JS 3.3.6 and opening the ZIM in trust mode? If not which version are you using?

**Comment by hamoudak** [comment] 2024-07-02 15:58
yes I am - Kiwix JS PWA 3.3.6. my op is windows 10 pro ; but now when I was browsing the file more than once , pages open normal, no problem with it ! anyway sorry for taking your time. I know you're busy with your stuff.

**Comment by benoit74** [comment] 2024-07-04 09:39
OK, let's close this issue then

**Closed by benoit74** 2024-07-04 09:39 UTC
